server:
  port: 8010    #port number

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  application:
    name: api-gateway

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
#        hystrix.stream, info, health

hystrix:
  dashboard:
    proxy-stream-allow-list: "*"

logging:
  level:
    com.self.sprintboot.learning.apigateway: DEBUG